### ISSUE TITLE
outdated icons

### ISSUE THREAD

**Issue by renatosc** [oneo-me/Fluent-System-Icons#1]
Hi. Thanks for creating this WPF compatible project. I noticed that the icons available are outdated (e.g: there is no "questioncircle20Regular" although that icon is available at the [master branch](https://github.com/microsoft/fluentui-system-icons/blob/master/icons.md) of Microsoft Fluent UI repo. It appears that you fixed your Assets to a now [outdated version](https://github.com/microsoft/fluentui-system-icons/tree/0cf1b6500225c81edf80593fc365557f5b90a528) of the icons.

**Comment by oneo-me** [comment]
I have just released version 1.0.1

**Comment by renatosc** [comment]
Wow, that was fast. I even forked to do a Pull Request for you. I guess it is not needed anymore.

**Comment by renatosc** [comment]
Btw, if you can, please add this github link to your FluentSystemIconsForWPF nuget package to make it easier to get here (I had found your nuget package first and then there was no link to source at the nuget package. I ended up finding your repo here by luck in one of the replies of an issue in the original microsoft repo)

**Comment by oneo-me** [comment]
Okay, I'll add the link when I have time
